apiVersion: v1
kind: Service
metadata:
  name: blob-service
spec:
  selector:
    app: blobs
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 3002
  ip-address: 192.168.0.111
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blobs
spec:
  selector:
    matchLabels:
      app: blobs
  template:
    metadata:
      labels:
        app: blobs
    spec:
      containers:
      - name: blobs
        image: theangelogarci/miapp
        imagePullPolicy: Never
        ports:
        - containerPort: 3002

