apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 3001
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: blob-service
spec:
  selector:
    app: blob
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 3002
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: dirs-service
spec:
  selector:
    app: dirs
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 3003
  type: NodePort

