apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob-deployment
spec:
  selector:
    matchLabels:
      app: blob
  template:
    metadata:
      labels:
        app: blob
    spec:
      containers:
      - name: blob
        image: theangelogarci/miapp
        ports:
        - containerPort: 3002